#!/usr/bin/env bash
set -e

# Configures the AWS CLI tools
#
# Usage:
#     configures-awscli ["us-west-2"]

# Load shared utils
. ./hg-circle-scripts/utils

region=$1
if [ -n $region ]; then
    region="us-west-2"
fi

log "Setting AWS defaults (region, output format)"
aws --version
aws configure set default.region $region
aws configure set default.output json
