#!/usr/bin/env bash
set -e

# Syncs the built directory to the supplied S3 path.
#
# Usage:
#     ui-cdn-deploy "<distribution id>"
#
# Example:
#     ui-cdn-deploy "E3QVKP0HM4DUY4"

# Load shared utils
. ./hg-circle-scripts/utils
bash ./hg-circle-scripts/configure-awscli

log "Creating CDN invalidations"
aws configure set preview.cloudfront true
INVALIDATION_ID=$((aws cloudfront create-invalidation --distribution-id "$1" --paths "/*") | jq -r .Invalidation.Id)

log "Created invalidation $INVALIDATION_ID. In Progress..."
aws cloudfront wait invalidation-completed --id $INVALIDATION_ID --distribution-id $1 
log "Invalidation $INVALIDATION_ID completed on distribution $1"
