#!/usr/bin/env bash
set -e

# Syncs the built directory to the supplied S3 path.
#
# Usage:
#     ui-cdn-deploy "<distribution id>"
#
# Example:
#     ui-cdn-deploy "E3QVKP0HM4DUY4"

# Load shared utils
. ./hg-circle-scripts/utils
bash ./hg-circle-scripts/configure-awscli

log "Creating CDN invalidations"
aws configure set preview.cloudfront true
aws cloudfront create-invalidation --distribution-id "$1" --paths /index.html
