#!/usr/bin/env bash

# Syncs the built directory to the supplied S3 path.
#
# Usage:
#     ui-cdn-deploy "<distribution id>"
#
# Example:
#     ui-cdn-deploy "E3QVKP0HM4DUY4"

##
# Log to the CLI with the current timestamp
# @param: message
##
log() {
    echo "$(date "+%Y-%m-%d %H:%M:%S"): $1"
}

sh ./hg-circle-scripts/install-awscli

log "Creating CDN invalidations"
aws configure set preview.cloudfront true
aws cloudfront create-invalidation --distribution-id "$1" --paths /index.html