#!/usr/bin/env bash

# Syncs the built directory to the supplied S3 path.
#
# Usage:
#     ui-deploy "<S3 path>" "<current branch>" ["<comma separated list of ignored branches>"] ["<region>"]
#
# Example:
#     ui-deploy "hg-cf-accounts-ui" "master" "master,stage,live" "us-west-2"

##
# Log to the CLI with the current timestamp
# @param: message
##
log() {
    echo "$(date "+%Y-%m-%d %H:%M:%S"): $1"
}

sh ./hg-circle-scripts/install-awscli

s3_path=$1
current_branch=$2

if [ -n $3 ]; then
    # Default to these..
    ignored_branches=("master" "stage" "live")
else
    ignored_branches=$(echo $3 | tr "," "\n")
fi

region=$4
if [ -n $region ]; then
    region="us-west-2"
fi

# Set the static path for feature branches
if [[ "${ignored_branches[*]}" != *"$current_branch"* ]]; then
    # https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#building-for-relative-paths
    S3_URL="http://s3-website-${region}.amazonaws.com/${s3_path}/${current_branch}"
    echo $(jq "setpath([\"homepage\"]; \"${S3_URL}\")" "package.json") > "package.json"
fi

log "Building static files"
yarn run build

# @todo: Once S3 object tagging is out of beta, tag all synced objects with env/purpose
log "Deploying to S3"
aws s3 sync build/ "s3://${s3_path}/${current_branch}" --region $region