#!/usr/bin/env bash
set -e

# Runs the front-end tests
#
# Usage:
#     ui-tests

# Load shared utils
. ./hg-circle-scripts/utils

log "Installing dependencies"
yarn  # Install dependencies first

log "Running ESLint"
yarn run eslint .

log "Running tests"
yarn test
