#!/usr/bin/env bash
set -e

# Load shared utils
. ./hg-circle-scripts/utils
. ./hg-circle-scripts/db/pg/utils

##
# Ensures we have a postgres database group (role), suppressing duplicate errors if needs be.
##

# Check all args are passed
if [ $# -ne 5 ]; then
    echo "Must supply all arguments. Exiting..."
    echo 'Usage: ensure-pg-db "<host prefix>" "<master username>" "<master password>" "<db name>" "<group name>"'
    echo ''
    echo 'Eg. ensure-pg-db-group "api-dev" "postgres" "abc123" "api-db" "read"'
    exit 1
fi

DB_HOST_PREFIX=$1
DB_MASTER_USERNAME=$2
DB_MASTER_PASSWORD=$3
DB_NAME=$4
GROUP_NAME=$5

DB_HOST="${DB_HOST_PREFIX}.pg.hugoai.com"  # Keeps things consistently applied!

log "Creating group \"${GROUP_NAME}\" on host \"${DB_HOST}\""

# Not passing LOGIN to CREATE ROLE makes it a "group" role :)
read -d '' sql << EOF
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='${GROUP_NAME}') THEN
        CREATE ROLE ${GROUP_NAME};
    END IF;
END
\$\$;
EOF
execute_sql "$sql"
